import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const readJson=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const listJson=dir=>fs.existsSync(dir)?fs.readdirSync(dir).filter(f=>f.endsWith('.json')).map(f=>readJson(path.join(dir,f))):[];
const products=listJson(path.join(root,'content/products')).filter(x=>x.status==='published');
const articles=listJson(path.join(root,'content/articles')).filter(x=>x.status==='published');

function head(title,desc){return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=Be+Vietnam+Pro:wght@400;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/css/style.css"></head>`}
function header(current=''){const active=k=>current===k?' aria-current="page"':'';return `<header class="site-header"><div class="container nav"><a class="brand" href="/index.html"><img src="/assets/images/logo.jpg" alt="Logo Shop Uyên Ương"><span class="brand-name">UYÊN ƯƠNG</span></a><button class="menu-btn" type="button" aria-label="Mở menu" onclick="toggleMenu()">☰</button><nav class="nav-links" id="mobileMenu" aria-label="Điều hướng chính"><a href="/index.html"${active('home')}>Trang chủ</a><a href="/san-pham/mam-qua-cuoi-tphcm.html"${active('mamqua')}>Mâm quả cưới</a><a href="/index.html#banh-cuoi-hoi"${active('banhcuoi')}>Bánh cưới hỏi</a><a href="/san-pham/banh-phuc-linh-tphcm.html"${active('phuclinh')}>Bánh phục linh</a><a href="/index.html#cam-nang"${active('camnang')}>Cẩm nang</a><a href="/index.html#lien-he">Liên hệ</a><a class="cart-link" href="/gio-hang.html">Giỏ hàng <span class="cart-badge" data-cart-count>0</span></a><a class="nav-order" href="/dat-hang.html">Đặt hàng</a></nav></div></header>`}
function footer(){return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><div class="footer-brand"><img src="/assets/images/logo.jpg" alt="Logo Shop Uyên Ương"><div><div class="brand-name">UYÊN ƯƠNG</div><p>Đồng hành cùng những khoảnh khắc hạnh phúc</p></div></div><div class="footer-meta"><p>31/42 Phạm Hùng, Bình Hưng, Bình Chánh, TP. Hồ Chí Minh</p><p>Điện thoại/Zalo: 0868 157 858</p><p><a class="footer-social-link" href="https://www.facebook.com/mamquacuoihcm/" target="_blank" rel="noopener">Facebook Shop Uyên Ương – Mâm quả cưới HCM ↗</a></p><p><a class="footer-social-link" href="https://www.facebook.com/Banhphuclinhhcm/?locale=vi_VN" target="_blank" rel="noopener">Facebook Bánh phục linh HCM ↗</a></p></div></div><div><div class="footer-title">Bánh cưới hỏi</div><div class="footer-links"><a href="/san-pham/banh-phu-the-hue-tphcm.html">Bánh phu thê Huế</a><a href="/san-pham/banh-phu-the-mien-bac-tphcm.html">Bánh phu thê miền Bắc</a></div></div><div><div class="footer-title">Mâm quả cưới</div><div class="footer-links"><a href="/san-pham/mam-qua-cuoi-tphcm.html">Gói 4 mâm</a><a href="/san-pham/mam-qua-cuoi-tphcm.html">Gói 6 mâm</a><a href="/san-pham/mam-qua-cuoi-tphcm.html">Gói 8 mâm</a><a href="/san-pham/mam-qua-cuoi-tphcm.html">Theo yêu cầu</a></div></div><div><div class="footer-title">Cẩm nang & Hỗ trợ</div><div class="footer-links"><a href="/index.html#cam-nang">Cẩm nang cưới</a><a href="/dat-hang.html">Đặt hàng</a><a href="/gio-hang.html">Giỏ hàng</a></div></div></div><div class="footer-bottom"><span>© 2026 Shop Uyên Ương.</span><span>Uyên Ương – Kết nối những khoảnh khắc hạnh phúc ♥</span></div></div></footer><div class="mobile-actions"><a href="tel:0868157858">Gọi</a><a class="primary" href="https://zalo.me/0868157858">Zalo</a><a href="/dat-hang.html">Đặt hàng</a></div><script src="/assets/js/app.js"></script>`}

function productCard(p){
  const d1=p.details?.[0]?.value||'';const d2=p.details?.[1]?.value||'';
  let meta=p.price_text||'Giá liên hệ';
  if(p.id==='mamqua')meta=p.details?.find(d=>/Đặt trước/i.test(d.label))?.value||meta;
  else if(p.quantity?.min>1)meta=`${p.price_text||'Giá liên hệ'} • Nhận từ ${p.quantity.min} ${p.quantity.unit||''}`;
  return `<article class="product-card"><a href="/san-pham/${esc(p.slug)}.html"><img src="${esc(p.image)}" alt="${esc(p.name)}"></a><div class="product-body"><h3>${esc(p.name)}</h3><div class="spec">${esc([d1,d2].filter(Boolean).join(' • '))}</div><div class="meta-line">${esc(meta)}</div><div class="product-actions"><a class="btn btn-primary btn-block" href="/san-pham/${esc(p.slug)}.html">Xem chi tiết</a></div></div></article>`;
}
function articleCard(a){return `<article class="article-card"><img src="${esc(a.thumbnail)}" alt="${esc(a.title)}"><div><h3>${esc(a.title)}</h3><p>${esc(a.excerpt)}</p><a href="/cam-nang/${esc(a.slug)}.html">Xem bài viết →</a></div></article>`}

function replaceBetween(text,startMarker,endMarker,replacement){const s=text.indexOf(startMarker),e=text.indexOf(endMarker);if(s<0||e<0||e<s)throw new Error(`Không tìm thấy marker ${startMarker}`);return text.slice(0,s+startMarker.length)+'\n'+replacement+'\n'+text.slice(e)}

const indexPath=path.join(root,'index.html');
let index=fs.readFileSync(indexPath,'utf8');
const featured=products.filter(p=>p.featured).sort((a,b)=>(a.featured_order??99)-(b.featured_order??99)).slice(0,8);
const homeArticles=articles.filter(a=>a.featured).sort((a,b)=>(a.featured_order??99)-(b.featured_order??99)).slice(0,6);
index=replaceBetween(index,'<!-- CMS_PRODUCTS_START -->','<!-- CMS_PRODUCTS_END -->',`<div class="featured-grid" id="banh-cuoi-hoi">${featured.map(productCard).join('')}</div>`);
index=replaceBetween(index,'<!-- CMS_ARTICLES_START -->','<!-- CMS_ARTICLES_END -->',`<div class="guides-grid">${homeArticles.map(articleCard).join('')}</div>`);
fs.writeFileSync(indexPath,index);

function optionFields(p){return (p.option_groups||[]).map(g=>`<div class="field"><label for="${esc(g.key)}">${esc(g.label)}</label><select id="${esc(g.key)}" name="${esc(g.key)}">${(g.values||[]).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select></div>`).join('')}
function detailRows(p){return (p.details||[]).map(d=>`<div><dt>${esc(d.label)}</dt><dd>${esc(d.value)}</dd></div>`).join('')}
function featureRows(p){return (p.features||[]).map(x=>`<li>${esc(x)}</li>`).join('')}
function faqRows(p){return (p.faq||[]).map(x=>`<div class="faq-item"><h3>${esc(x.question)}</h3><p>${esc(x.answer)}</p></div>`).join('')}
function productPage(p){
  const q=p.quantity||{label:'Số lượng',unit:'',min:1,default:1,step:1,hint:''};
  const current=p.id==='mamqua'?'mamqua':p.id==='phuclinh'?'phuclinh':'banhcuoi';
  const pdata=JSON.stringify(p).replace(/</g,'\\u003c');
  const priceHint=(p.price_mode==='hybrid'||(p.price_rules||[]).length)?'<div id="product-price-hint" class="notice"></div>':'';
  return `${head(p.seo?.title||p.name,p.seo?.description||p.short_description||'') }<body>${header(current)}<main><div class="container"><div class="breadcrumb"><a href="/index.html">Trang chủ</a><span>›</span><a href="/index.html#san-pham-noi-bat">Sản phẩm</a><span>›</span>${esc(p.name)}</div><section class="product-detail"><div class="product-gallery"><div class="product-main-image"><img id="mainProductImage" src="${esc(p.image)}" alt="${esc(p.name)}"></div></div><div class="product-info-panel"><div class="eyebrow">Sản phẩm Shop Uyên Ương · TPHCM</div><h1>${esc(p.name)}</h1><p class="lead">${esc(p.lead||p.short_description||'')}</p><div class="detail-price">${esc(p.price_text||'Giá liên hệ')}</div><dl class="detail-list">${detailRows(p)}</dl><form class="purchase-box" id="product-purchase" onsubmit="return false"><h2>Chọn sản phẩm để gửi yêu cầu</h2>${optionFields(p)}<div class="field"><label>${esc(q.label)}</label><div class="qty-wrap"><button type="button" data-qty-minus>−</button><input name="qty" type="number" min="${Number(q.min||1)}" step="${Number(q.step||1)}" value="${Number(q.default||q.min||1)}"><button type="button" data-qty-plus>+</button></div>${q.hint?`<small>${esc(q.hint)}</small>`:''}</div>${priceHint}<div class="purchase-actions"><button class="btn btn-secondary" type="button" data-add-cart>Thêm vào giỏ</button><button class="btn btn-primary" type="button" data-buy-now>Đặt ngay</button></div><p class="purchase-hint">Mua 1 món: chọn <strong>Đặt ngay</strong>. Mua nhiều món: chọn <strong>Thêm vào giỏ</strong>.</p></form><script type="application/json" id="product-data">${pdata}</script></div></section><section class="content-section"><div class="content-card"><div class="eyebrow">Thông tin sản phẩm</div><h2>Điểm cần biết trước khi đặt</h2><ul class="feature-list">${featureRows(p)}</ul></div></section><section class="content-section"><div class="content-card"><div class="eyebrow">Giải đáp nhanh</div><h2>Thông tin thường được khách hỏi</h2><div class="faq-list">${faqRows(p)}</div></div></section><section class="section-sm"><div class="contact-panel"><div><h2>Cần Shop tư vấn thêm?</h2><p>Liên hệ Shop Uyên Ương để xác nhận giá, số lượng và yêu cầu trước khi làm.</p></div><div class="contact-actions"><a class="btn btn-secondary" href="tel:0868157858">Gọi 0868 157 858</a><a class="btn btn-primary" href="https://zalo.me/0868157858">Chat Zalo</a></div></div></section></div></main>${footer()}</body></html>`;
}

fs.mkdirSync(path.join(root,'san-pham'),{recursive:true});
for(const p of products){fs.writeFileSync(path.join(root,'san-pham',`${p.slug}.html`),productPage(p))}

function articlePage(a){return `${head(a.seo?.title||a.title,a.seo?.description||a.excerpt||'')}<body>${header('camnang')}<main><div class="container article-layout"><div class="breadcrumb"><a href="/index.html">Trang chủ</a><span>›</span><a href="/index.html#cam-nang">Cẩm nang</a><span>›</span>${esc(a.title)}</div><div class="article-hero"><img src="${esc(a.thumbnail)}" alt="${esc(a.title)}"></div><article class="article-content"><div class="eyebrow">Cẩm nang cưới</div><h1>${esc(a.title)}</h1><p>${esc(a.excerpt||'')}</p>${a.body||''}<div class="contact-panel" style="margin-top:24px;"><div><h2>Cần Shop tư vấn thêm?</h2><p>Liên hệ Shop Uyên Ương để được hỗ trợ cụ thể theo nhu cầu của gia đình.</p></div><div class="contact-actions"><a class="btn btn-secondary" href="tel:0868157858">Gọi điện</a><a class="btn btn-primary" href="https://zalo.me/0868157858">Chat Zalo</a></div></div></article></div></main>${footer()}</body></html>`}
fs.mkdirSync(path.join(root,'cam-nang'),{recursive:true});
for(const a of articles){fs.writeFileSync(path.join(root,'cam-nang',`${a.slug}.html`),articlePage(a))}

console.log(`Đã build ${products.length} sản phẩm và ${articles.length} bài viết.`);
