function cloneOption(option) {
  return {
    id: option.id,
    label: option.label,
    ...(option.default === true ? { default: true } : {}),
    ...(option.allow_custom_text === true ? { allow_custom_text: true, custom_placeholder: option.custom_placeholder } : {})
  };
}

function cloneOptionGroup(group) {
  return {
    id: group.id,
    name: group.name,
    type: group.type,
    required: group.required !== false,
    options: group.options.map(cloneOption)
  };
}

function cloneComponent(component) {
  return {
    id: component.id,
    label: component.label,
    ...(component.sub_option ? { sub_option: cloneOptionGroup(component.sub_option) } : {}),
    ...(component.allow_custom_text === true ? { allow_custom_text: true, custom_placeholder: component.custom_placeholder } : {})
  };
}

export function createProductCatalog(products = []) {
  const catalog = {};
  for (const product of products.filter(item => item.status === 'published')) {
    catalog[product.id] = {
      id: product.id,
      name: product.name,
      slug: product.slug,
      type: product.type,
      main_image: product.main_image,
      short_description: product.short_description,
      price: {
        mode: product.price.mode,
        display_text: product.price.display_text,
        ...(product.price.mode === 'fixed' ? { amount: product.price.amount } : {}),
        ...(product.price.mode === 'hybrid' ? { rules: product.price.rules.map(rule => ({ ...rule })) } : {})
      },
      quantity: product.quantity,
      option_groups: (product.option_groups || []).map(cloneOptionGroup),
      components: (product.components || []).map(cloneComponent),
      receive_date: product.receive_date || { enabled: false },
      note: product.note || { enabled: false }
    };
  }
  return catalog;
}

export function browserCatalogSource(products = []) {
  return `window.UYEN_UONG_PRODUCTS=${JSON.stringify(createProductCatalog(products))};\n`;
}

export function serverCatalogSource(products = []) {
  return `// Generated by v2/scripts/build.mjs. Do not edit by hand.\nexport const PRODUCT_CATALOG=${JSON.stringify(createProductCatalog(products), null, 2)};\n`;
}
